/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladormovimientocurvilineo;

import ecuaciones.Polinomio;

/**
 *
 * @author usuario
 */
public class VentanaConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConfiguracion
     */
    private boolean ocultarPosicion = false;
    private boolean ocultacele = false;
    private boolean ocultaveloc = false;
    private boolean ocultime = false;
    private boolean ocultBtnReporte = false;
    
    public VentanaConfiguracion() {
        initComponents();
        this.ocultarPosicion = VentanaPrincipal.txtfPosX.isVisible();
        this.ocultacele      = VentanaPrincipal.txtfAcel.isVisible();
        this.ocultaveloc     = VentanaPrincipal.txtfVel.isVisible();
        this.ocultime        = VentanaPrincipal.txtfTiempo.isVisible();
        this.ocultBtnReporte = VentanaPrincipal.btnReportes.isVisible();
        
        this.cambiarEstadoCombos();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCalcularAceleracion = new javax.swing.JButton();
        btnCalcularVelocidad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        posicionSelect = new javax.swing.JComboBox<>();
        txtEcuacionPosicion = new javax.swing.JTextField();
        txtEcuacionVelocidad = new javax.swing.JTextField();
        txtEcuacionAceleracion = new javax.swing.JTextField();
        labelPosicion = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        velocidadSelect = new javax.swing.JComboBox<>();
        aceleracionSelect = new javax.swing.JComboBox<>();
        tiempoSelect = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        reporteSelect = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 300, -1, -1));

        btnCalcularAceleracion.setText("Calcular");
        btnCalcularAceleracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularAceleracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        btnCalcularVelocidad.setText("Calcular");
        btnCalcularVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularVelocidadActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel2.setText("Ecuacion de velocidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 30));

        jLabel4.setText("Ecuacion de posición:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 58, 140, 30));

        jLabel5.setText("Ecuacion de aceleración:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("CALCULADORA DE ECUACIONES POLINÓMICAS:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 23, 310, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setLabelFor(posicionSelect);
        jLabel11.setText("OPCIONES:");
        jLabel11.setPreferredSize(new java.awt.Dimension(52, 50));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 80, 20));

        posicionSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOSTRAR", "OCULTAR" }));
        posicionSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionSelectActionPerformed(evt);
            }
        });
        getContentPane().add(posicionSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 61, 110, -1));

        txtEcuacionPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcuacionPosicionActionPerformed(evt);
            }
        });
        getContentPane().add(txtEcuacionPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 120, 30));

        txtEcuacionVelocidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEcuacionVelocidad.setDragEnabled(true);
        txtEcuacionVelocidad.setEnabled(false);
        txtEcuacionVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcuacionVelocidadActionPerformed(evt);
            }
        });
        getContentPane().add(txtEcuacionVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 120, 30));

        txtEcuacionAceleracion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEcuacionAceleracion.setDragEnabled(true);
        txtEcuacionAceleracion.setEnabled(false);
        getContentPane().add(txtEcuacionAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 120, 30));

        labelPosicion.setText("Posición");
        getContentPane().add(labelPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 70, 20));

        jLabel12.setText("Velocidad");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 109, 70, 20));

        jLabel13.setText("Aceleración");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 151, 70, 20));

        jLabel14.setText("Tiempo");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(412, 199, 70, 20));

        velocidadSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOSTRAR", "OCULTAR" }));
        velocidadSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                velocidadSelectActionPerformed(evt);
            }
        });
        getContentPane().add(velocidadSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 106, 110, -1));

        aceleracionSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOSTRAR", "OCULTAR" }));
        aceleracionSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceleracionSelectActionPerformed(evt);
            }
        });
        getContentPane().add(aceleracionSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 148, 110, -1));

        tiempoSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOSTRAR", "OCULTAR" }));
        tiempoSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiempoSelectActionPerformed(evt);
            }
        });
        getContentPane().add(tiempoSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 196, 110, -1));

        jLabel6.setText("Reportes");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 70, 20));

        reporteSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HABILITAR", "INHABILITAR" }));
        reporteSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteSelectActionPerformed(evt);
            }
        });
        getContentPane().add(reporteSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 110, -1));

        setSize(new java.awt.Dimension(666, 379));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEcuacionPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcuacionPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcuacionPosicionActionPerformed

    private void txtEcuacionVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcuacionVelocidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcuacionVelocidadActionPerformed

    private void posicionSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionSelectActionPerformed
        int id = posicionSelect.getSelectedIndex();
        ocultarPosicion = id == 1;
    }//GEN-LAST:event_posicionSelectActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(ocultarPosicion == true){
            VentanaPrincipal.labelPosicionX.setVisible(false);
            VentanaPrincipal.txtfPosX.setVisible(false);
            VentanaPrincipal.labelPosicionY.setVisible(false);
            VentanaPrincipal.txtfPosY.setVisible(false);
        }
        else{
            VentanaPrincipal.labelPosicionX.setVisible(true);
            VentanaPrincipal.txtfPosX.setVisible(true);
            VentanaPrincipal.labelPosicionY.setVisible(true);
            VentanaPrincipal.txtfPosY.setVisible(true);
        }
        if(ocultaveloc == true){
            VentanaPrincipal.LabelVelocidad.setVisible(false);
            VentanaPrincipal.txtfVel.setVisible(false);
        }
        else{
            VentanaPrincipal.LabelVelocidad.setVisible(true);
            VentanaPrincipal.txtfVel.setVisible(true);   
        }
        if(ocultacele == true){
            VentanaPrincipal.LabelAceleración.setVisible(false);
            VentanaPrincipal.txtfAcel.setVisible(false);
        }
        else{
            VentanaPrincipal.LabelAceleración.setVisible(true);
            VentanaPrincipal.txtfAcel.setVisible(true);   
        }
        if(ocultime == true){
            VentanaPrincipal.LabelTiempo.setVisible(false);
            VentanaPrincipal.txtfTiempo.setVisible(false);
        }
        else{
            VentanaPrincipal.LabelTiempo.setVisible(true);
            VentanaPrincipal.txtfTiempo.setVisible(true);   
        }
        if(ocultBtnReporte){
            VentanaPrincipal.btnReportes.setVisible(false);
        }else{
            VentanaPrincipal.btnReportes.setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void velocidadSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_velocidadSelectActionPerformed
        // TODO add your handling code here:
         int id = velocidadSelect.getSelectedIndex();
        if(id == 1){
            ocultaveloc = true;
        }else{
            ocultaveloc = false;
        }
    }//GEN-LAST:event_velocidadSelectActionPerformed

    private void aceleracionSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceleracionSelectActionPerformed
        // TODO add your handling code here:
         int id = aceleracionSelect.getSelectedIndex();
        if(id == 1){
            ocultacele = true;
        }else{
            ocultacele=false;
        }
    }//GEN-LAST:event_aceleracionSelectActionPerformed

    private void tiempoSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiempoSelectActionPerformed
        // TODO add your handling code here
        int id = tiempoSelect.getSelectedIndex();
        ocultime = id == 1;
    }//GEN-LAST:event_tiempoSelectActionPerformed

    private void reporteSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteSelectActionPerformed
        int id = reporteSelect.getSelectedIndex();
        ocultBtnReporte = id == 1;
    }//GEN-LAST:event_reporteSelectActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCalcularVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularVelocidadActionPerformed
        Polinomio velocidad;
        txtEcuacionVelocidad.setText("");
        try{
            velocidad =new Polinomio(txtEcuacionPosicion.getText()).getDerivada();
            txtEcuacionVelocidad.setText(velocidad.toString());
            txtEcuacionVelocidad.setEnabled(true);
        }catch(Exception e){
            System.out.println("Ocurrió un error");
            txtEcuacionVelocidad.setEnabled(false);
        }
    }//GEN-LAST:event_btnCalcularVelocidadActionPerformed

    private void btnCalcularAceleracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularAceleracionActionPerformed
        Polinomio aceleracion;
        txtEcuacionAceleracion.setText("");
        try{
            aceleracion =new Polinomio(txtEcuacionPosicion.getText()).getDerivada().getDerivada();
            txtEcuacionAceleracion.setText(aceleracion.toString());
            txtEcuacionAceleracion.setEnabled(true);
        }catch(Exception e){
            System.out.println("Ocurrió un error");
            txtEcuacionAceleracion.setEnabled(false);
        }
    }//GEN-LAST:event_btnCalcularAceleracionActionPerformed
    
    private void cambiarEstadoCombos(){
        if(ocultarPosicion)posicionSelect.setSelectedIndex(0);
        else posicionSelect.setSelectedIndex(1);
        
        if(ocultacele)aceleracionSelect.setSelectedIndex(0);
        else aceleracionSelect.setSelectedIndex(1);
        
        if(ocultaveloc)velocidadSelect.setSelectedIndex(0);
        else velocidadSelect.setSelectedIndex(1);
        
        if(ocultime) tiempoSelect.setSelectedIndex(0);
        else tiempoSelect.setSelectedIndex(1);
        
        if(ocultBtnReporte)reporteSelect.setSelectedIndex(0);
        else reporteSelect.setSelectedIndex(1);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConfiguracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConfiguracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> aceleracionSelect;
    private javax.swing.JButton btnCalcularAceleracion;
    private javax.swing.JButton btnCalcularVelocidad;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelPosicion;
    private javax.swing.JComboBox<String> posicionSelect;
    private javax.swing.JComboBox<String> reporteSelect;
    private javax.swing.JComboBox<String> tiempoSelect;
    private javax.swing.JTextField txtEcuacionAceleracion;
    private javax.swing.JTextField txtEcuacionPosicion;
    private javax.swing.JTextField txtEcuacionVelocidad;
    private javax.swing.JComboBox<String> velocidadSelect;
    // End of variables declaration//GEN-END:variables
}
