/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladormovimientocurvilineo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JFrame;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


/**
 *
 * @author USUARIO1
 */
public class VentanaReportes extends javax.swing.JFrame {
 
    
    private final ChartPanel chartPanel;
    private final XYSeries valoresGrafica = new XYSeries("");
    private final HashMap<String, List<List<Double>>> reportes;
    private String etiquetaXChart = "";
    private String etiquetaYChart = "";
    private String tituloChart = "";
    /**
     * Creates new form VentanaReportes
     */
    
    private ChartPanel crearChart(List<List<Double>> lista){

      crearSeries(lista);
      XYSeriesCollection col = crearColeccion(valoresGrafica);
      JFreeChart chartGrafica = ChartFactory.createXYLineChart(
        tituloChart,etiquetaXChart,etiquetaYChart,col
      );
      
      ChartPanel panel = new ChartPanel(chartGrafica);
      
      return panel;
    }
    
    private XYSeriesCollection crearColeccion(XYSeries series){
        XYSeriesCollection coleccionDeDatos = 
              new XYSeriesCollection(series);
        return coleccionDeDatos;
    }
    
    public void crearSeries(List<List<Double>> valores){
        //map.entrySet().forEach((item) -> {
        //    valoresGrafica.addOrUpdate(item.getKey(),item.getValue());
        //});
        valores.forEach((item)->{
            valoresGrafica.addOrUpdate(item.get(0), item.get(1));
        });
        
    }
    
    private float getMax(List<Double> t){
        double max = 0;
        for (int i = 0; i < t.size(); i++) {
            if (t.get(i) > max) {
                max = t.get(i);
            }
        }
        return (float)max;
    }
    
    public VentanaReportes(HashMap<String, List<List<Double>>> reportes, HashMap<String, List<Double>> reportesUnicos){
        initComponents();
        
        this.reportes = reportes;
        List<List<Double>> listaVacia = new ArrayList<>();
        chartPanel = crearChart(listaVacia);
        chartPanel.setSize(500,300);
        chartPanel.setVisible(true);
        chartPanel.setLocation(280,60);
        add(chartPanel);
        crearSeries(reportes.get("velocidad-tiempo"));
        
        etiquetaX.setText("Velocidad");
        etiquetaY.setText("Tiempo");
        
        this.txtReportesVelocidad.setText(Float.toString(this.getMax(reportesUnicos.get("velocidades"))));
        this.txtReportesAceleracion.setText(Float.toString(this.getMax(reportesUnicos.get("aceleraciones"))));
        this.txtReportesPosicionX.setText(Float.toString(this.getMax(reportesUnicos.get("posicionesx"))));
        this.txtReportesPosicionY.setText(Float.toString(this.getMax(reportesUnicos.get("posicionesy"))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtReportesVelocidad = new javax.swing.JTextField();
        txtReportesAceleracion = new javax.swing.JTextField();
        txtReportesPosicionX = new javax.swing.JTextField();
        txtReportesPosicionY = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        etiquetaX = new javax.swing.JLabel();
        etiquetaY = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte de datos");
        setMaximumSize(new java.awt.Dimension(1024, 601));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Datos máximos (MKS):");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Velocidad máxima");
        jLabel2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Aceleración máxima");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("REPORTE GENERAL");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Posición X Máxima");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Posición Y Máxima");

        txtReportesVelocidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReportesVelocidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtReportesVelocidad.setEnabled(false);
        txtReportesVelocidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportesVelocidadActionPerformed(evt);
            }
        });

        txtReportesAceleracion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReportesAceleracion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtReportesAceleracion.setEnabled(false);

        txtReportesPosicionX.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReportesPosicionX.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtReportesPosicionX.setEnabled(false);
        txtReportesPosicionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReportesPosicionXActionPerformed(evt);
            }
        });

        txtReportesPosicionY.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtReportesPosicionY.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtReportesPosicionY.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("RELACIÓN DE DATOS");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Velocidad vs Tiempo", "Aceleración vs Tiempo", "Posición X vs Posición Y" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        etiquetaX.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        etiquetaX.setText("Etiqueta X");

        etiquetaY.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        etiquetaY.setText("Etiqueta Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel9))
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(22, 22, 22)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtReportesVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtReportesPosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtReportesPosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtReportesAceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(172, 172, 172)
                                    .addComponent(etiquetaY)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(jLabel10)))
                        .addGap(144, 145, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(etiquetaX, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtReportesVelocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReportesAceleracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtReportesPosicionX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtReportesPosicionY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(etiquetaY, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(etiquetaX)
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );

        setSize(new java.awt.Dimension(816, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtReportesPosicionXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportesPosicionXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportesPosicionXActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        int ind = jComboBox1.getSelectedIndex();
        List<List<Double>> lista = new ArrayList<>();
        valoresGrafica.clear();
        switch(ind){
            case 0://VELOCIDAD VS TIEMPO
               lista = reportes.get("velocidad-tiempo");
               tituloChart = "Velocidad(m/s) vs Tiempo(s)";
               etiquetaXChart = "Velocidad";
               etiquetaYChart = "Tiempo";
               break;
            case 1://ACELERACION VS TIEMPO
               lista = reportes.get("aceleracion-tiempo"); 
               tituloChart = "Aceleración(m/s^2) vs Tiempo(s)";
               etiquetaXChart = "Aceleración";
               etiquetaYChart = "Tiempo";
               break;
            case 2://POSICIÓN X VS POSICIÓN Y
               lista = reportes.get("x-y");
               tituloChart = "Posición X(m) vs Posición Y(m)";
               etiquetaXChart = "Posición X";
               etiquetaYChart = "Posición Y";
               break;
        }
         etiquetaX.setText(etiquetaXChart);
         etiquetaY.setText(etiquetaYChart);
         crearSeries(lista);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void txtReportesVelocidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReportesVelocidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReportesVelocidadActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> {
        //    new VentanaReportes().setVisible(true);
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaX;
    private javax.swing.JLabel etiquetaY;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtReportesAceleracion;
    private javax.swing.JTextField txtReportesPosicionX;
    private javax.swing.JTextField txtReportesPosicionY;
    private javax.swing.JTextField txtReportesVelocidad;
    // End of variables declaration//GEN-END:variables
}
