/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simuladormovimientocurvilineo;

/**
 *
 * @author Jibaru
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setTitle("Simulador Movimiento Curvilíneo Plano");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        planoCartesiano1 = new simuladormovimientocurvilineo.PlanoCartesiano();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        labelXValues = new javax.swing.JLabel();
        labelYValues = new javax.swing.JLabel();
        labelTiempoMax = new javax.swing.JLabel();
        txtEcuacionX = new javax.swing.JTextField();
        txtEcuacionY = new javax.swing.JTextField();
        txtEcuacionTiempo = new javax.swing.JTextField();
        btnReportes = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        comboEstilos = new javax.swing.JComboBox();
        btnPausar = new javax.swing.JButton();
        btnTerminar = new javax.swing.JButton();
        labelPosicionX = new javax.swing.JLabel();
        LabelVelocidad = new javax.swing.JLabel();
        LabelTiempo = new javax.swing.JLabel();
        txtfPosX = new javax.swing.JTextField();
        txtfVel = new javax.swing.JTextField();
        txtfTiempo = new javax.swing.JTextField();
        LabelPosiciónY = new javax.swing.JLabel();
        LabelAceleración = new javax.swing.JLabel();
        txtfPosY = new javax.swing.JTextField();
        txtfAcel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        labelPosicion = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        labelEcuacionVelocidad = new javax.swing.JLabel();
        txtEcuacionVelocidad = new javax.swing.JTextField();
        labelEcuacionAceleracion = new javax.swing.JLabel();
        txtEcuacionAceleracion = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCambiarPosInicial = new javax.swing.JToggleButton();
        txtPosInicialX = new javax.swing.JTextField();
        txtPosInicialY = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout planoCartesiano1Layout = new javax.swing.GroupLayout(planoCartesiano1);
        planoCartesiano1.setLayout(planoCartesiano1Layout);
        planoCartesiano1Layout.setHorizontalGroup(
            planoCartesiano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 658, Short.MAX_VALUE)
        );
        planoCartesiano1Layout.setVerticalGroup(
            planoCartesiano1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );

        getContentPane().add(planoCartesiano1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 76, -1, -1));

        jLabel4.setText("(0,0)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 328, -1, -1));

        jLabel5.setFont(new java.awt.Font("Raleway SemiBold", 0, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><b>SIMULADOR MOVIMIENTO CURVILÍNEO PLANO</b></html>");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 22, 987, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 43, 120, -1));

        labelXValues.setText("Valores en X");
        getContentPane().add(labelXValues, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 100, -1));

        labelYValues.setText("Valores en Y");
        getContentPane().add(labelYValues, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 90, -1));

        labelTiempoMax.setText("Tiempo máximo");
        getContentPane().add(labelTiempoMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 100, -1));

        txtEcuacionX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEcuacionXActionPerformed(evt);
            }
        });
        getContentPane().add(txtEcuacionX, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, 140, -1));
        getContentPane().add(txtEcuacionY, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 140, -1));
        getContentPane().add(txtEcuacionTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, 140, -1));

        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        getContentPane().add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 180, -1));

        btnConfiguracion.setText("Configuracion");
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        getContentPane().add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 180, -1));

        jLabel10.setText("Estilos");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 340, -1, -1));

        comboEstilos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Fondo 1", "Fondo 2", "Fondo 3", "Cuadricula" }));
        comboEstilos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstilosActionPerformed(evt);
            }
        });
        getContentPane().add(comboEstilos, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 340, 130, -1));

        btnPausar.setText("PAUSAR");
        btnPausar.setEnabled(false);
        btnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPausarActionPerformed(evt);
            }
        });
        getContentPane().add(btnPausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 180, -1));

        btnTerminar.setText("TERMINAR");
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTerminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 460, 180, -1));

        labelPosicionX.setText("Posicion X");
        getContentPane().add(labelPosicionX, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 50, 20));

        LabelVelocidad.setText("Velocidad");
        getContentPane().add(LabelVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, -1, 20));

        LabelTiempo.setText("Tiempo");
        getContentPane().add(LabelTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, 20));

        txtfPosX.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfPosX.setEnabled(false);
        txtfPosX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPosXActionPerformed(evt);
            }
        });
        getContentPane().add(txtfPosX, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 140, 30));

        txtfVel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfVel.setEnabled(false);
        getContentPane().add(txtfVel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 140, 30));

        txtfTiempo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfTiempo.setDoubleBuffered(true);
        txtfTiempo.setEnabled(false);
        getContentPane().add(txtfTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 140, 30));

        LabelPosiciónY.setText("Posición Y");
        getContentPane().add(LabelPosiciónY, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, 20));

        LabelAceleración.setText("Aceleración");
        getContentPane().add(LabelAceleración, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 20));

        txtfPosY.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfPosY.setEnabled(false);
        txtfPosY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfPosYActionPerformed(evt);
            }
        });
        getContentPane().add(txtfPosY, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 140, 30));

        txtfAcel.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtfAcel.setEnabled(false);
        txtfAcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfAcelActionPerformed(evt);
            }
        });
        getContentPane().add(txtfAcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 430, 140, 30));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("DATOS INICIALES");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, 180, -1));

        labelPosicion.setText("Tiempo de simulación");
        getContentPane().add(labelPosicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        jLabel18.setText("INFORMACIÓN DE LA SIMULACIÓN:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, -1, 20));

        labelEcuacionVelocidad.setText("Ecuación velocidad");
        getContentPane().add(labelEcuacionVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 110, -1));

        txtEcuacionVelocidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEcuacionVelocidad.setEnabled(false);
        getContentPane().add(txtEcuacionVelocidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 180, 140, -1));

        labelEcuacionAceleracion.setText("Ecuación aceleración");
        getContentPane().add(labelEcuacionAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 110, -1));

        txtEcuacionAceleracion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtEcuacionAceleracion.setEnabled(false);
        getContentPane().add(txtEcuacionAceleracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 210, 140, -1));

        btnIniciar.setText("INICIAR");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 380, 180, -1));

        jLabel1.setText("Plano Cartesiano");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Posición Inicial");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 90, -1));

        btnCambiarPosInicial.setText("Cambiar");
        btnCambiarPosInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarPosInicialActionPerformed(evt);
            }
        });
        getContentPane().add(btnCambiarPosInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 90, -1));

        txtPosInicialX.setText("0");
        getContentPane().add(txtPosInicialX, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 40, -1));

        txtPosInicialY.setText("0");
        getContentPane().add(txtPosInicialY, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 40, -1));

        setSize(new java.awt.Dimension(1040, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEcuacionXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEcuacionXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEcuacionXActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        VentanaReportes ventanaReportes = new VentanaReportes();
        ventanaReportes.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        VentanaConfiguracion ventanaConfiguracion = new VentanaConfiguracion();
        ventanaConfiguracion.setVisible(true);
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void txtfPosYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPosYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPosYActionPerformed

    private void comboEstilosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstilosActionPerformed
        String path = null;
        int indice = comboEstilos.getSelectedIndex();
        switch(indice){
            case 0:
               path = "src/assets/img/fondo1.jpg";
               break;
            case 1:
               path = "src/assets/img/fondo2.jpg";
               break;
            case 2:
               path = "src/assets/img/fondo3.png";
            case 3:
               path = "src/assets/img/cuadricula.jpg";
               break;
        }
        this.planoCartesiano1.setImageBackground(path);
    }//GEN-LAST:event_comboEstilosActionPerformed

    private void btnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPausarActionPerformed
        if(isSuspended){
            this.planoCartesiano1.resume();
            btnPausar.setText("PAUSAR");
            this.isSuspended = false;
        } else {
            this.planoCartesiano1.suspend();
            btnPausar.setText("CONTINUAR");
            this.isSuspended = true;
        }
    }//GEN-LAST:event_btnPausarActionPerformed

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        this.planoCartesiano1.stop();
        btnIniciar.setEnabled(true);
        btnPausar.setEnabled(false);
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void txtfPosXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfPosXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfPosXActionPerformed

    private void txtfAcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfAcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfAcelActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        planoCartesiano1.restart();
        btnIniciar.setEnabled(false);
        btnPausar.setEnabled(true);
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnCambiarPosInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarPosInicialActionPerformed
 
        int x = Integer.parseInt(this.txtPosInicialX.getText());
        int y = Integer.parseInt(this.txtPosInicialY.getText());
        
        planoCartesiano1.setObjectPosition(x, y);
    }//GEN-LAST:event_btnCambiarPosInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });

    }
    private boolean isSuspended = false;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel LabelAceleración;
    public static javax.swing.JLabel LabelPosiciónY;
    public static javax.swing.JLabel LabelTiempo;
    public static javax.swing.JLabel LabelVelocidad;
    private javax.swing.JToggleButton btnCambiarPosInicial;
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPausar;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnTerminar;
    private javax.swing.JComboBox comboEstilos;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelEcuacionAceleracion;
    private javax.swing.JLabel labelEcuacionVelocidad;
    public static javax.swing.JLabel labelPosicion;
    public static javax.swing.JLabel labelPosicionX;
    private javax.swing.JLabel labelTiempoMax;
    private javax.swing.JLabel labelXValues;
    private javax.swing.JLabel labelYValues;
    private simuladormovimientocurvilineo.PlanoCartesiano planoCartesiano1;
    private javax.swing.JTextField txtEcuacionAceleracion;
    private javax.swing.JTextField txtEcuacionTiempo;
    private javax.swing.JTextField txtEcuacionVelocidad;
    private javax.swing.JTextField txtEcuacionX;
    private javax.swing.JTextField txtEcuacionY;
    private javax.swing.JTextField txtPosInicialX;
    private javax.swing.JTextField txtPosInicialY;
    public static javax.swing.JTextField txtfAcel;
    public static javax.swing.JTextField txtfPosX;
    public static javax.swing.JTextField txtfPosY;
    public static javax.swing.JTextField txtfTiempo;
    public static javax.swing.JTextField txtfVel;
    // End of variables declaration//GEN-END:variables
}
